# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='disease',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
