# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_clinic', '0002_patients_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='password',
            field=models.CharField(default=' ', max_length=6),
        ),
    ]
